#%RAML 0.8
---
title: CherAmi API
baseUri: http://localhost:8228/api/

/users:
  get:
  post:
  /{id}:
    get:
    post:
    delete:
    /reputation:
      get:
      post:
/sessions:
  post:
  delete:
/circles:
  get:
  post:
/circle:
  /{id}:
    get:
    post:
    /members:
      post:
    /blocked:
      get:
      post:
/messages:
  get:
  post:
  /{id}:
    get:
    delete:
    /comments:
      get:
      post:
      /{id}:
        get:
        delete:

